### ISSUE TITLE
Isn't the acceptance time dependent on server load?

### ISSUE THREAD

**Issue by narang-madhur** [Rishabh2804/DSA-Practice#1]

**Comment by narang-madhur** [comment]
Yes it affects but it usually affects equally for all!

**Comment by Rishabh2804** [comment]
Yes, it sure does, for instance, a submission on Leetcode might give a submission runtime of 1ms at first go, and again submitting the exact same code might result a runtime of 5ms. Not sure about working of this extension though.

**Comment by narang-madhur** [comment]
> Yes, it sure does, for instance, a submission on Leetcode might give a submission runtime of 1ms at first go, and again submitting the exact same code might result a runtime of 5ms. Not sure about working of this extension though.

Exactly!
